# Generated by Django 4.1.13 on 2024-01-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
